# Generated by Django 4.0.6 on 2022-08-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('primary_role', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('bio', models.TextField()),
                ('number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('linkd_url', models.URLField()),
                ('past_exp', models.TextField()),
                ('add_det', models.TextField()),
                ('status', models.CharField(default='applied', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, null=True, upload_to='resume/')),
                ('frel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detail')),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
