# Generated by Django 4.0.6 on 2022-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detail_resume_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='number',
            field=models.CharField(max_length=80),
        ),
    ]
